"use client";
import type { PilotEvidenceSnapshot } from "@/lib/types";
import { useLocale } from "@/lib/i18n/LocaleProvider";

export function PilotEvidenceReview({ snapshot }: { snapshot: PilotEvidenceSnapshot }) { return <article className="mx-auto max-w-5xl space-y-5 rounded-xl border border-neutral-800 bg-neutral-950 p-5" data-testid="pilot-evidence-review"><PilotEvidenceReviewHeader snapshot={snapshot}/><EvidenceReadinessStrip snapshot={snapshot}/><PilotLimitationsPanel snapshot={snapshot}/><BehavioralEvidenceGrid snapshot={snapshot}/><BuyerReactionPanel snapshot={snapshot}/><RegionalEvidenceSplit snapshot={snapshot}/><CommercialProgressionPanel snapshot={snapshot}/><EvidenceDisputeTimeline snapshot={snapshot}/><PilotProvenanceSummary snapshot={snapshot}/></article>; }
export function PilotEvidenceReviewHeader({snapshot}:{snapshot:PilotEvidenceSnapshot}) { const {dict}=useLocale(); return <header data-testid="pilot-header"><h1 className="text-xl font-semibold text-neutral-50">{dict.pilotReview.title}</h1><p className="mt-1 text-sm text-neutral-300" dir="auto">{dict.pilotReviewContent.aliases[snapshot.alias]} · {snapshot.pilotId} · {snapshot.snapshotId}</p><p className="mt-1 text-xs text-neutral-400">{dict.freshness[snapshot.freshness]}</p><p className="mt-2 text-xs text-amber-200" dir="auto">{dict.pilotReview.noAuthority}</p></header>; }
export function EvidenceReadinessStrip({snapshot}:{snapshot:PilotEvidenceSnapshot}) { const {dict}=useLocale(); return <section data-testid="pilot-readiness" className="grid gap-3 rounded-lg border border-sky-900 p-4 sm:grid-cols-5"><Metric label={dict.pilotReview.readiness} value={dict.pilotReview.states[snapshot.readiness]}/><Metric label={dict.pilotReview.validatedEpisodes} value={`${snapshot.validatedEpisodes} / ${snapshot.validatedEpisodes + snapshot.excludedEpisodes}`}/><Metric label={dict.pilotReview.excludedEpisodes} value={String(snapshot.excludedEpisodes)}/><Metric label={dict.pilotReview.companies} value={String(snapshot.distinctCompanies)}/><Metric label={dict.pilotReview.observationWindow} value={dict.pilotReviewContent.observationWindows[snapshot.observationWindow]}/></section>; }
export function PilotLimitationsPanel({snapshot}:{snapshot:PilotEvidenceSnapshot}) {const {dict}=useLocale();return <section data-testid="pilot-limitations"><h2>{dict.pilotReview.limitations}</h2><ul className="mt-2 list-disc space-y-1 ps-5 text-sm text-neutral-300">{snapshot.limitations.map(x=><li key={x} dir="auto">{dict.pilotReview.limitationsCopy[x as keyof typeof dict.pilotReview.limitationsCopy]}</li>)}</ul></section>;}
export function BehavioralEvidenceGrid({snapshot}:{snapshot:PilotEvidenceSnapshot}) {const {dict}=useLocale();const denominators={nextStepReady:snapshot.validatedEpisodes,noAction:snapshot.validatedEpisodes,restraintRespected:snapshot.behavior.noAction,chasingViolation:snapshot.behavior.noAction,buyerSignalAfterRestraint:snapshot.behavior.restraintRespected,buyerSignalAfterChasing:snapshot.behavior.chasingViolation};return <section data-testid="pilot-behavior"><h2>{dict.pilotReview.behavioralEvidence}</h2><div className="mt-2 grid gap-2 sm:grid-cols-3">{(Object.entries(snapshot.behavior) as Array<[keyof typeof snapshot.behavior,number]>).map(([k,v])=><Metric key={k} label={dict.pilotReview.behaviorLabels[k]} value={`${v} / ${denominators[k]}`}/>)}</div><p className="mt-2 text-xs text-neutral-400">{dict.pilotReview.descriptiveOnly}</p></section>;}
export function BuyerReactionPanel({snapshot}:{snapshot:PilotEvidenceSnapshot}){const {dict}=useLocale();return <section data-testid="pilot-buyer-reaction"><h2>{dict.pilotReview.buyerReaction}</h2><p className="text-sm text-neutral-200" dir="auto"><span>{dict.pilotReview.buyerReactionStates[snapshot.buyerReaction]}</span> · <span>{dict.pilotReview.descriptiveOnly}</span></p></section>;}
export function RegionalEvidenceSplit({snapshot}:{snapshot:PilotEvidenceSnapshot}){const {dict}=useLocale();return <section data-testid="pilot-regions"><h2>{dict.pilotReview.regionalSplit}</h2><div className="mt-2 grid gap-3 sm:grid-cols-2">{Object.entries(snapshot.regions).map(([region,value])=><Metric key={region} label={dict.pilotReviewContent.regions[region as keyof typeof dict.pilotReviewContent.regions]} value={`${value.numerator} / ${value.denominator}; ${value.excluded}; ${dict.pilotReview.regionStates[value.state]}`}/>)}</div></section>;}
export function CommercialProgressionPanel({snapshot}:{snapshot:PilotEvidenceSnapshot}){const {dict}=useLocale();return <section data-testid="pilot-commercial"><h2>{dict.pilotReview.commercialProgression}</h2><p className="text-sm text-neutral-200" dir="auto"><span>{dict.pilotReview.commercialStates[snapshot.commercial]}</span> · <span>{dict.pilotReview.limitationsCopy.commercialLimit}</span></p></section>;}
export function EvidenceDisputeTimeline({snapshot}:{snapshot:PilotEvidenceSnapshot}){const {dict}=useLocale();return <section data-testid="pilot-dispute"><h2>{dict.pilotReview.disputeTimeline}</h2><p className="text-sm text-neutral-200">{dict.pilotReview.disputeStates[snapshot.dispute]}</p>{snapshot.correctionSnapshotId && snapshot.correctionSnapshotId !== snapshot.snapshotId?<p className="text-xs text-neutral-400">{dict.pilotReview.previous}: {snapshot.snapshotId} · {dict.pilotReview.current}: {snapshot.correctionSnapshotId}</p>:null}</section>;}
export function PilotProvenanceSummary({snapshot}:{snapshot:PilotEvidenceSnapshot}){const {dict}=useLocale();return <footer><h2>{dict.pilotReview.provenance}</h2><p className="text-xs text-neutral-500" dir="auto">{dict.pilotReviewContent.provenance[snapshot.provenance]}</p></footer>;}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded border border-neutral-800 p-3"><p className="text-xs text-neutral-500" dir="auto">{label}</p><p className="mt-1 text-sm text-neutral-100" dir="auto">{value}</p></div>}
